env:
  - secure: "IR5WeCvorDp1JweLSAtAKiW9YQ3I4PeWSi543DMOM1E5GZ1Z3TnmNxawxhSS\nGLt3hP/O4LDaSaGi14Ercb8Km/6qB6uVJ++ULVayVRLBK+N0XbKi3gIsViYv\nX1537Ia6PJjCkijVr7c8UFKj0+vfV4UPw64hEw8efAXjHrqlBYI="

script: "./deploy.sh"
